/** PostgreSQL (self-hosted) provider bundle: local JWT auth + Postgres storage. */
module.exports = {
  authProvider: require('./authProvider'),
  assetService: require('./assetService'),
  ticketService: require('./ticketService'),
  problemService: require('./problemService'),
  changeService: require('./changeService'),
  requestTemplateService: require('./requestTemplateService'),
  kbService: require('./kbService'),
  handoverService: require('./handoverService'),
  maintenanceService: require('./maintenanceService'),
  dashboardService: require('./dashboardService'),
  employeeService: require('./employeeService'),
  orgService: require('./orgService'),
  approvalService: require('./approvalService'),
  inappService: require('./inappService'),
  offboardService: require('./offboardService'),
  onboardingService: require('./onboardingService'),
  licenseService: require('./licenseService'),
  consumableService: require('./consumableService'),
  settingsService: require('./settingsService'),
  documentService: require('./documentService'),
  catalogService: require('./catalogService'),
  countService: require('./countService'),
  lineService: require('./lineService'),
  importService: require('./importService'),
  zimmetImportService: require('./zimmetImportService'),
  auditService: require('./auditService'),
  providerService: require('./providerService'),
  notificationService: require('./notificationService'),
  customFieldService: require('./customFieldService'),
  apiKeyService: require('./apiKeyService'),
  webhookService: require('./webhookService'),
  syncService: require('./syncService'),
  permissionService: require('./permissionService'),
  migrationService: require('./migrationService'),
  selfService: require('./selfService'),
  hrRequestService: require('./hrRequestService'),
  aiConfigService: require('./aiConfigService'),
  ensureDatabase: () => require('./migrate').ensureDatabase(),
  ping: (timeoutMs) => require('./pool').ping(timeoutMs),
  isAuthError: (err) => require('./pool').isAuthError(err),
};
