apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-pull-ext
  namespace: itacm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault      # Kendi ClusterSecretStore veya SecretStore adını yaz
    kind: ClusterSecretStore  # Kendi yapına göre (SecretStore da olabilir)
  target:
    name: harbor-pull         # Deployment'ın arayacağı secret'ın adı
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        # Vault'tan gelen şifreyi Docker Config formatına gömüyoruz
        .dockerconfigjson: |
          {
            "auths": {
              "harbor.itacm.site": {
                "username": "robot$itacm+jenkins",
                "password": "{{ .robot_password }}"
              }
            }
          }
  data:
    - secretKey: robot_password
      remoteRef:
        key: secret/itacm     # Vault'taki secret yolu (kendi path'ine göre düzelt)
        property: robot_password
